### ISSUE TITLE
Re-organize the code for modularity

### ISSUE THREAD

**Issue by shz9** [shz9/gwasimulator#3]
Currently, the GWASDataLoader class incorporates many functionalities that make it brittle and harder to work with. We would like to move some of those functionalities into their own classes/objects.

Here are a number of ideas that we can implement:

- [x] Move summary statistics to their own class `SumStats`
- [x] Move LD functionalities to their own class `LD`
- [x] Move annotations to their own class 'Annotations`
- [x] (Need discussion) Move genotypes to their own class `Genotype`

In this sort of setup, the GWASDataLoader object would be an interface to harmonize these data classes, instead of performing many different, unrelated functions.

**Comment by dorukcakmakci** [comment]
While these changes make code more modular, development can get messy quickly. How about we write a test for GWASSimulator class to ensure it preserves its functionality before tackling this issue?

**Comment by shz9** [comment]
Most of this refactoring was done in `magenpy==0.0.2`.
